# Generated by Django 3.2 on 2021-04-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarKata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kosakata', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengingat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul', models.CharField(max_length=15)),
                ('topik_tugas', models.CharField(max_length=220)),
                ('tenggat', models.DateField()),
                ('jenis_tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.daftarkata')),
            ],
        ),
    ]
